# Generated by Django 6.0.6 on 2026-06-16 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('movie', '电影'), ('tv', '电视剧'), ('animation', '动漫'), ('animated_film', '剧场版')], max_length=100, verbose_name='类型')),
                ('douban_id', models.CharField(max_length=20, unique=True, verbose_name='豆瓣ID')),
                ('title', models.CharField(max_length=255, verbose_name='名称')),
                ('douban_url', models.URLField(verbose_name='豆瓣链接')),
                ('douban_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='豆瓣评分')),
                ('area', models.CharField(blank=True, max_length=20, verbose_name='片区')),
                ('imdb_id', models.CharField(blank=True, max_length=20, verbose_name='IMDb')),
                ('summary', models.TextField(blank=True, verbose_name='剧情简介')),
                ('poster_locate', models.ImageField(blank=True, upload_to='posters/', verbose_name='海报位置')),
                ('episodes', models.PositiveIntegerField(blank=True, null=True, verbose_name='集数')),
                ('seasons', models.PositiveIntegerField(blank=True, null=True, verbose_name='季数')),
                ('release_date_with_locations', models.JSONField(blank=True, default=list, verbose_name='上映日期（地点）')),
                ('runtime', models.PositiveIntegerField(blank=True, null=True, verbose_name='时长(分钟)')),
                ('release_years', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='上映年份')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='上映日期')),
                ('release_ear', models.CharField(blank=True, max_length=20, verbose_name='上映年代')),
                ('alias', models.ManyToManyField(blank=True, to='media_view.alias', verbose_name='又名')),
                ('countries', models.ManyToManyField(blank=True, to='media_view.country', verbose_name='制片国家/地区')),
                ('genres', models.ManyToManyField(blank=True, to='media_view.genre', verbose_name='类型')),
                ('actors', models.ManyToManyField(blank=True, related_name='acted_medias', to='media_view.person', verbose_name='主演')),
                ('director', models.ManyToManyField(blank=True, related_name='directed_medias', to='media_view.person', verbose_name='导演')),
                ('writers', models.ManyToManyField(blank=True, related_name='written_medias', to='media_view.person', verbose_name='编剧')),
            ],
            options={
                'verbose_name': '影视',
                'verbose_name_plural': '影视',
                'ordering': ['-douban_rating'],
            },
        ),
    ]
